const ProjectsDatas = [
  {
    id: "0",
    title: "Les Maux Sous La Peau – Court métrage documentaire",
    desc: "Les Maux Sous La Peau est un court métrage documentaire réalisé par Anne Roux, qui explore les souffrances intimes et invisibles des individus à travers des témoignages poignants. Ce film vise à sensibiliser le public à ces douleurs enfouies, en combinant un travail d’enquête et une approche artistique forte.",
    type: "Documentaire",
    img: "/images/projet-anne.PNG",
    src: "https://vimeo.com/961111352?share=copy",
    teaser: "",
    format: "Court-métrage",
    softwares: "After Effects, DaVinci Resolve",
    desc2: {
      1: "Réalisation des trucages incluant incrustation et rotoscopie avec After Effects pour renforcer la dimension visuelle et émotionnelle.",
      2: "Assemblage et montage final avec DaVinci Resolve.",
    },
  },
  {
    id: "1",
    title: "Vidéos promotionnelles pour levée de fonds 2025",
    desc: "Pour cette campagne de levée de fonds sur LinkedIn, j’ai monté une série de vidéos percutantes et engageantes visant à sensibiliser entreprises et ONG au projet Le Balai. Chaque vidéo a été optimisée pour un format court avec des sous-titres lisibles et un montage dynamique qui capte l’attention du public en ligne.",
    img: "/images/projet-lebalai.jpg",
    src: "https://www.linkedin.com/posts/ornella-djoukui-0705376a_100jourspourlebalai-impactsocial-innovationculturelle-activity-7304789068398092288-x6iV",
    teaser: "/videos/teaser-lebalai.mp4",
    type: "Vidéos promotionnelles pour les réseaux",
    format: "Vidéos courtes",
    softwares: "Premiere Pro, Photoshop",
    desc2: {
      1: "Montage vidéo orienté storytelling pour captiver l’audience professionnelle.",
      2: "Optimisation du format pour réseaux sociaux avec intégration de sous-titres accessibles.",
    },
  },

  {
    id: "2",
    title: "Film Kroskel - Collection Automne-Hiver 2025",
    desc: "Ce court-métrage promotionnel met en avant la nouvelle collection automne-hiver 2025 de Kroskel à travers un storytelling immersif. J’ai géré l’intégralité du montage, de l’assemblage des séquences à l’habillage graphique, en passant par l’étalonnage et la correction colorimétrique pour sublimer l’univers visuel de la marque.",
    img: "/images/projet-kroskel-ah.JPG",
    src: "https://www.youtube.com/embed/QfJ2HLXMBlA",
    teaser: "",
    type: "Fiction",
    format: "Court métrage",
    softwares: "Premiere Pro, Photoshop",
    desc2: {
      1: "Montage complet des séquences vidéo selon le storyboard.",
      2: "Création de l’habillage graphique pour renforcer l’identité visuelle de la marque.",
      3: "Étalonnage et correction colorimétrique pour une harmoniser l'esthétique.",
    },
  },
  {
    id: "3",
    title: "Documentaire Kroskel 2022",
    desc: "La maison de création a été fondée par Ornella DJOUKUI qui a, au fil des années, créé une équipe passionnée de professionnell·es de la mode. Derrière Kroskel, aujourd’hui, il y a deux équipes constituées principalement de femmes : une équipe de trois personnes en France qui se charge de la conception des collections, de la stratégie de la marque, de la communication et de la distribution. Et, une équipe plus large au Cameroun qui se charge de la recherche et de la réalisation des tissus teintés, de la transformation sur patron des modèles, de la réalisation, du contrôle qualité et de l’expédition.",
    img: "/images/projet-kroskel-doc.jpg",
    src: "https://www.youtube.com/embed/BSQ6TZKi258",
    teaser: "/videos/teaser-kroskel-doc.mp4",
    type: "Documentaire",
    format: "Court-métrage",
    softwares: "Premiere Pro",
    desc2: {
      1: "Montage et assemblage des interviews et images terrain.",
      2: "Optimisation du rythme narratif pour valoriser les équipes et le savoir-faire.",
      3: "Insertion de graphiques et éléments visuels pour contextualiser les étapes de production.",
    },
  },
  {
    id: "4",
    title: "Vidéos promotionnelles pour la collection Les Incontournables 2022",
    desc: "En parallèle de mon poste de développeuse chez Kroskel, j’ai conçu et monté plusieurs vidéos pour Instagram et Facebook, mettant en avant les collections, l’atelier de fabrication au Cameroun et le savoir-faire artisanal de la marque. Je vous laisse découvrir les vidéos sur le compte Instagram et YouTube de la marque Kroskel entre 2022 et 2023. Pour mettre en lumière Les Incontournables, une collection emblématique de Kroskel, j’ai réalisé une série de vidéos promotionnelles destinées aux réseaux sociaux. L’objectif était de capturer l’essence de ces pièces intemporelles à travers un montage rythmé et immersif, mettant en valeur le savoir-faire artisanal et l’élégance des créations.",
    img: "/images/projet-kroskel-incontournables.jpg",
    src: "https://www.instagram.com/reel/CoUJAuhICZQ/",
    teaser: "",
    type: "Vidéos promotionnelles pour les réseaux sociaux",
    format: "Vidéos courtes",
    softwares: "Premiere Pro, Photoshop, Blender, Illustrator",
    desc2: {
      1: "Conception et montage de vidéos dynamiques adaptées aux formats Instagram et Facebook.",
      2: "Mise en valeur du savoir-faire artisanal par un montage immersif et rythmé.",
      3: "Gestion de la colorimétrie pour refléter l’identité visuelle des collections.",
    },
  },
  {
    id: "5",
    title: "Les 99%",
    desc: "À travers Les Vlogs de Baltha, j’ai accompagné Balthazar dans son aventure nordique en transformant ses images brutes en récits immersifs et captivants. Chaque semaine, je recevais ses vidéos de voyage et les montais pour raconter son expérience authentique de la Finlande, entre découvertes culturelles, paysages enneigés et anecdotes de voyage.",
    img: "/images/projet-les99.PNG",
    src: "https://youtu.be/-y600xmQWCU?si=vXuQg-pfunGBEBHF",
    teaser: "",
    type: "Websérie",
    format: "Série d'épisodes courts",
    softwares: "Premiere Pro, Photoshop",
    desc2: {
      1: "Montage hebdomadaire des séquences reçues pour en faire des récits cohérents et captivants.",
      2: "Gestion de la narration visuelle pour mettre en avant les paysages et moments forts.",
      3: "Intégration de musique et effets sonores pour renforcer l’immersion.",
    },
  },
  {
    id: "6",
    title: "Les Vlogs de Baltha",
    desc: "À travers Les Vlogs de Baltha, j’ai accompagné Balthazar dans son aventure nordique en transformant ses images brutes en récits immersifs et captivants. Chaque semaine, je recevais ses vidéos de voyage et les montais pour raconter son expérience authentique de la Finlande, entre découvertes culturelles, paysages enneigés et anecdotes de voyage.",
    img: "/images/projet-baltha.PNG",
    src: "https://www.youtube.com/embed/CWaKChtIMRk",
    teaser: "",
    type: "Vlogs",
    format: "Vidéos courtes pour YouTube",
    softwares: "Premiere Pro, Photoshop",
    desc2: {
      1: "Montage hebdomadaire des séquences reçues pour en faire des récits cohérents et captivants.",
      2: "Gestion de la narration visuelle pour mettre en avant les paysages et moments forts.",
      3: "Intégration de musique et effets sonores pour renforcer l’immersion.",
    },
  },
    {
    id: "7",
    title: "Kroksel - Collection Printemps-Été 2023 ",
    desc: "La collection Girasole célèbre le renouveau et l’énergie du printemps à travers des pièces vibrantes et élégantes. Pour promouvoir cette collection, j’ai conçu et monté une série de vidéos immersives qui alternent entre plans détaillés et plans larges. L'objectif de cette campagne était de mettre en avant le tissu lumineux des créations.",
    img: "/images/projet-girasole.jpg",
    src: "https://www.instagram.com/p/Cq3Tyy5Idb0/",
    teaser: "/videos/teaser-girasol.mp4",
    type: "Vidéos promotionnelles",
    format: "Linkedin",
    softwares: "Premiere Pro, Photoshop",
    desc2: {
      1: "Conception et montage de vidéos mettant en valeur la texture et la luminosité des tissus.",
      2: "Alternance entre plans rapprochés et plans larges pour un storytelling visuel.",
      3: "Gestion de la colorimétrie pour traduire l’esprit printanier de la collection.",
    },
  },

  {
    id: "8",
    title: "Court métrage Des Livres Et Moi",
    desc: "J'ai réalisé le montage de ce court-métrage écrit par Anne ROUX, réalisé lors du confinement en 2022.",
    img: "/images/projet-deslivresetmoi.PNG",
    src: "https://www.youtube.com/embed/2vvbX68--60",
    teaser: "",
    type: "Vidéos promotionnelles",
    format: "Linkedin",
    softwares: "Premiere Pro",
    desc2: {
      1: "Montage intégral du court métrage en respectant le scénario et le rythme souhaité.",
      2: "Travail sur la cohérence narrative et le rythme des scènes.",
      3: "Optimisation de la qualité visuelle par étalonnage basique.",
    },
  },
  {
    id: "9",
    title: "A TAAABLE ! Etc... - Un podcast sonore propulsé par Wuman",
    desc: "Co-réalisé avec Anne Roux, ce podcast documentaire itinérant explore les récits de vie à travers les habitudes alimentaires des invités. J’ai assuré la post-production sonore pour garantir une écoute fluide et immersive.",
    img: "/images/projet-atable.jpg",
    src: "https://soundcloud.com/wumanne",
    teaser: "",
    type: "Vidéos promotionnelles",
    format: "Linkedin",
    softwares: "Audacity, Photoshop",
    desc2: {
      1: "Post-production sonore complète : nettoyage audio, équilibrage des niveaux et mixage.",
      2: "Insertion de jingles et transitions pour fluidifier l’écoute.",
      3: "Optimisation du rendu sonore pour différents supports de diffusion.",
    },
  },
];

export default ProjectsDatas;
